# Atividade Prática - ENEM

In [1]:
import pandas as pd
import numpy as np
import zipfile
import requests
from io import BytesIO
import os

In [4]:
# Cria um diretório para armazenar o conteúdo do enade
os.makedirs('./enem2019', exist_ok=True)

# Define a url e faz o download do conteúdo
url = "http://download.inep.gov.br/microdados/microdados_enem_2019.zip"
filebytes = BytesIO(requests.get(url, stream=True).content)

# Extrai o conteúdo do zipfile
myzip = zipfile.ZipFile(filebytes)
myzip.extractall('./enem2019')

In [6]:
enem = pd.read_csv('enem2019/DADOS/MICRODADOS_ENEM_2019.csv', sep=';', decimal=',', encoding='latin1')

In [7]:
enem

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001004627,2019,1506807,Santarém,15,PA,21,M,1,3,...,A,A,A,C,B,A,D,A,B,A
1,190001004628,2019,1504059,Mãe do Rio,15,PA,16,F,1,3,...,A,A,A,B,B,A,B,A,A,A
2,190001004629,2019,1505502,Paragominas,15,PA,18,F,1,1,...,B,A,A,D,B,B,D,A,C,B
3,190001004630,2019,1507706,São Sebastião da Boa Vista,15,PA,23,M,0,3,...,A,A,A,C,A,A,D,A,A,A
4,190001004631,2019,1503903,Juruti,15,PA,23,M,1,3,...,A,A,A,B,A,A,D,A,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095265,190006129589,2019,2928604,Santo Amaro,29,BA,28,F,2,2,...,A,A,A,B,A,A,B,A,A,B
5095266,190006129590,2019,2927408,Salvador,29,BA,25,M,1,2,...,A,A,A,A,A,A,B,A,A,A
5095267,190006129591,2019,2931806,Tremedal,29,BA,18,F,1,3,...,A,A,A,B,A,A,B,A,A,B
5095268,190006129592,2019,2927408,Salvador,29,BA,16,M,1,1,...,B,A,A,B,B,A,C,A,B,B
5095269,190006129593,2019,2914802,Itabuna,29,BA,25,F,1,2,...,B,A,B,B,B,A,B,A,B,B

In [8]:
enemmg = enem.loc[enem.SG_UF_RESIDENCIA == 'MG']

In [9]:
enemmg

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
1044,190001005671,2019,3170206,Uberlândia,31,MG,21,M,1,1,...,B,A,A,D,A,A,D,B,B,B
5234,190001009861,2019,3111705,Canaã,31,MG,20,M,1,1,...,A,A,A,B,A,A,C,A,A,A
16995,190001021622,2019,3104007,Araxá,31,MG,24,M,1,2,...,A,A,A,C,B,A,C,A,A,B
22008,190001026636,2019,3106200,Belo Horizonte,31,MG,33,M,1,1,...,B,A,B,B,A,A,D,A,D,B
22114,190001026742,2019,3162401,São João da Ponte,31,MG,23,M,1,3,...,A,A,A,B,B,A,C,A,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5095256,190006120182,2019,3170107,Uberaba,31,MG,59,F,2,2,...,A,A,A,B,A,A,C,A,B,B
5095257,190006120183,2019,3162708,São João do Paraíso,31,MG,33,F,0,1,...,B,A,A,B,A,A,B,A,B,B
5095258,190006120184,2019,3112604,Capinópolis,31,MG,18,F,1,2,...,B,A,B,D,B,B,D,A,B,B
5095259,190006120185,2019,3154606,Ribeirão das Neves,31,MG,22,F,2,3,...,B,A,A,B,A,A,C,A,A,B
5095260,190006120186,2019,3106705,Betim,31,MG,37,F,1,3,...,A,A,A,C,B,A,D,A,B,B

In [10]:
# Salvando um csv apenas do enem de MG
enemmg.to_csv('enem2019/enemmg.csv', index=False)

In [2]:
enemmg = pd.read_csv('enem2019/enemmg.csv')

In [3]:
import sqlalchemy

In [4]:
engine = sqlalchemy.create_engine(
    "mssql+pyodbc://SA:Ney198789@127.0.0.1/enem?driver=ODBC+Driver+17+for+SQL+Server"
)

In [5]:
%%time
enemmg.to_sql('desempenho', con=engine, index=False, if_exists='append', chunksize=1000)

CPU times: user 2min 11s, sys: 16.4 s, total: 2min 27s
Wall time: 10min 22s

# vamos deletar o enem completão para guardar memória
del(enem)